"""initialization

Revision ID: 81a97c49be34
Revises: 
Create Date: 2024-11-13 18:37:04.898839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81a97c49be34'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('files', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('storage_path', sa.String(length=255), nullable=True))
    #     batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
