"""Add deleted_at to File and Folder

Revision ID: bb7cd784ef3c
Revises: 15a852622e76
Create Date: 2024-11-12 15:45:04.549721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb7cd784ef3c'
down_revision = '15a852622e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_accessed')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
