"""initialization

Revision ID: c36519a4ca71
Revises: 
Create Date: 2024-11-12 12:11:26.656045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c36519a4ca71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_items')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('recent_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recent_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recent_items_pkey')
    )
    # ### end Alembic commands ###
