"""Recreate alembic version

Revision ID: ef1f399a04a8
Revises: b3a18281c430
Create Date: 2024-11-19 18:20:44.267572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1f399a04a8'
down_revision = 'b3a18281c430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Set a default value for existing rows (e.g., 0 or another meaningful ID)
    op.execute('UPDATE files SET user_id = 1')  # Replace `1` with an appropriate value

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
